= Reference-fr

Reference-fr est le dépôt pour la documentation de la référence de langage de la syntaxe Arduino en **Français**.
Tous les fichiers de référence sont au format AsciiDoc.

Merci d'avoir pris le temps de contribuer au contenu Arduino, c'est très utile à toute la communauté Arduino. Si vous voulez en savoir plus sur la manière de contribuer à ce projet, rendez-vous sur https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37[ce tutoriel étape par étape].

== Création et édition de contenu
Si vous voulez contribuer à du nouveau contenu, créez un nouveau fichier (avec n'importe quel éditeur de texte ou de code) et enregistrez-le en tant que .adoc.
N'utilisez pas de parenthèses ou de caractères spéciaux dans le nom de fichier.
Dans https://raw.githubusercontent.com/arduino/reference-fr/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-fr/AsciiDoc_sample/AsciiDoc_Dictionary`] vous trouverez un aperçu de la syntaxe AsciiDoc. Cela inclut les Titres, Textes, Liens, Images, Tableaux, Code ainsi que divers élements intégrés (vidéos, diaporamas, audio et code). Vous pouvez le voir rendu https://www.arduino.cc/reference/en/asciidoc_sample/asciidoc_dictionary/asciidoc_template-dictionary/[ici].

Si vous souhaitez contribuer à la documentation de référence du langue Arduino ou modifier le contenu existant, vous trouverez deux modèles dans reference-fr/AsciiDoc_sample/Reference_Terms:

* Utilisez https://raw.githubusercontent.com/arduino/reference-fr/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Single_Entity.adoc[`AsciiDoc_Template-Single_Entity.adoc`] (rendu https://www.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-single_entity/[ici]) pour des termes tels que link:http://arduino.cc/en/Reference/AnalogWrite[analogWrite].
* Utilisez https://raw.githubusercontent.com/arduino/reference-fr/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Parent_Of_Entities.adoc[`AsciiDoc_Template-Parent_Of_Entities.adoc`] (rendu https://www.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-parent_of_entities/[ici]) pour des groupes de fonctions tels que link:http://arduino.cc/en/Reference/Serial[Serial].

Notez que chaque fichier de référence doit inclure au moins une description, un exemple de code et des liens vers d'autres informations pertinentes (section Voir Également).

Si vous avez besoin d'ajouter des images à l'AsciiDoc, créez un dossier appelé attachments dans le même répertoire que le fichier AsciiDoc. Les images peuvent être sauvegardées au format SVG et PNG, taille maximale 200KB.

== Contribuer au contenu sur Github
Si vous n'êtes pas familier avec Git, vous pouvez contribuer du contenu directement sur Github via leur interface en ligne. Nous avons mis au point un petit tutoriel pour vous montrer comment, https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37[REGARDEZ-LE!]

link:https://help.github.com/articles/editing-files-in-another-user-s-repository/[Vous pouvez également suivre ce guide] (écrit par l'équipe Github) pour apprendre à modifier un fichier .adoc et proposer un changement de fichier à l'équipe Arduino.
Lorsque vous suggérez une modification, suivez les instructions décrites dans les fichiers modèles de référence.


== Soumettre une pull request
Nous sommes heureux que vous souhaitiez contribuer à la Référence Arduino: c'est le meilleur moyen d'aider la communauté.

Votre contribution consiste à ajouter ou modifier du code existant ou des descriptions complètes, veuillez toujours vous référer à un ticket (issue) existant ou en ouvrir un nouveau avant de contribuer.

Veuillez noter que votre contribution à la Référence Arduino est sous licence Creative Commons Attribution-Share Alike 3.0 License. Voir https://creativecommons.org/licenses/by-sa/3.0/


=== Structure du dossier
[source]
----
reference-fr
├─ AsciiDoc_sample
│   ├── AsciiDoc_Dictionary
│   │   ├── AsciiDoc_Template-Dictionary.adoc
│   │   └── attachments
│   └── Reference_Terms
│       ├── AsciiDoc_Template-Parent_Of_Entities.adoc
│       ├── AsciiDoc_Template-Single_Entity.adoc
│       └── attachments
├── Language
│   ├── Functions
│   ├── Structure
│   └── Variables
├── LICENCE.md
└── README.adoc

----

Dans le dossier Language, l'arborescence de fichiers suit la même structure que dans link:https://www.arduino.cc/reference/en[la page web Référence de Langage]
