---
title: constants
categories: [ "Variables" ]
subCategories: [ "Constants" ]
---

= Constantes


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
== Description
Les constantes sont des expressions prédéfinies du langage Arduino. Elles sont utilisées pour faciliter la lecture des programmes. On classe les constantes en groupes : 

[float]
== Définition des Niveaux Logiques : true et false (Constantes Booléennes)
Il existe deux constantes utilisées pour représenter les niveaux logiques haut et bas en langage Arduino : `true`, et `false`.

[float]
=== false
`false` est la plus simple des deux à définir : c'est le niveau 0 (zéro).
[%hardbreaks]

[float]
=== true
On dit souvent que `true` est défini comme étant 1, ce qui est correct, mais true a une définition plus large. Tout entier non-nul est true, au sens de la logique Booléenne. De ce fait, -1, 2, et -200 sont tous définis comme true, au sens booléen.
[%hardbreaks]

Note : les constantes `true` et `false` sont écrites en miniscules, contrairement à `HIGH`, `LOW`, `INPUT`, et `OUTPUT`.
[%hardbreaks]

[float]
== Définition de niveaux de pins : HIGH et LOW
Lors de la lecture ou de l'écriture d'un pin numérique, seules deux valeurs sont possibles : `HIGH` et `LOW`.

[float]
=== HIGH
Le sens de `HIGH` (en parlant d'un pin) est différent si le pin est configuré comme `INPUT` (entrée) ou `OUTPUT` (sortie). Lorsqu'un pin est configuré comme `INPUT` avec link:../../../functions/digital-io/pinmode[pinMode()], ou lu avec link:../../../functions/digital-io/digitalRead[digitalRead()], l'Arduino (ATMega) va renvoyer `HIGH` si :

  - une tension supérieure à 3.0V est présente sur le pin (pour les cartes fonctionnant en 5V)
  - une tension supérieure à 2.0V est présente sur le pin (pour les cartes fonctionnant en 3.3V)
[%hardbreaks]

Un pin peut aussi être configuré comme INPUT avec `pinMode()`, et être forcé à l'état HIGH avec link:../../../functions/digital-io/digitalwrite[digitalWrite()]. Cela aura pour effet d'activer la résistance interne de pullup de 20K, ce qui va forcer le pin d'entrée à un état `HIGH`, à moins qu'il ne soit explicitement passé à l'état `LOW` par le circuit externe. Alternativement, cela peut être fait en passant l'argument `INPUT_PULLUP` à la fonction `pinMode()`, comme expliqué ci-dessous plus en détail, dans la section "Définition des modes des pins numériques : INPUT, INPUT_PULLUP, et OUTPUT".
[%hardbreaks]

Lorsqu'un pin est configuré comme OUTPUT avec `pinMode()`, et forcé à `HIGH` avec `digitalWrite()`, la tension du pin est :

  - 5 volts (pour les cartes fonctionnants en 5V)
  - 3.3 volts (pour les cartes fonctionnants en 3.3V)
  
Dans cet état, il peut fournir du courant, par exemple, pour allumer une LED qui serait connectée à la masse, via une résistance en série.
[%hardbreaks]

[float]
=== LOW
Le sens de `LOW` est aussi différent selon que le pin est configuré comme `INPUT` ou `OUTPUT`. Lorsqu'un pin est configuré comme `INPUT` avec `pinMode()`, et lu avec `digitalRead()`, l'Arduino (ATMega) va renvoyer LOW si : 

  - une tension inférieure à 1.5V est présente sur le pin (pour les cartes fonctionnants en 5V)
  - une tension ingérieure à 1.0V (approximativement) est présente sur le pin (pour les cartes fonctionnants en 3.3V)
  
Lorsqu'un pin est configuré comme `OUTPUT` avec `pinMode()`, et forcé à `LOW` avec `digitalWrite()`, la tension sur le pin sera de 0 volts (pour les cartes fonctionnant en 5V et en 3.3V). Dans cet état, le pin peut recevoir du courant, par exemple, pour allumer une LED qui serait connectée au +5V (ou +3.3V) via une résistance en série.
[%hardbreaks]

[float]
== Définition des modes des pins numériques : INPUT, INPUT_PULLUP, et OUTPUT
Les pins numériques peuvent être utilisés comme `INPUT`, `INPUT_PULLUP`, ou `OUTPUT`. Les changement de modes avec `pinMode()` changent le comportement électrique d'un pin.

[float]
=== Pins configurés comme INPUT
On dit que les pins de l'Arduino (ATMega) configurés comme `INPUT` (entrée) avec `pinMode()` sont dans un état de _haute impédance_. Les pins configurés comme `INPUT` ne tirent que très peu de courant ; ils sont équivalents à une résistance de 100 Megaohms devant le pin. Cela les rend utiles pour la lecture d'un capteur.
[%hardbreaks]

Si un pin est configuré en `INPUT`, et connecté à un interrupteur, alors lorsque l'interrupteur est ouvert, le pin est dit "flottant", ce qui a pour conséquence une valeur lue imprédictible. Dans le but d'assurer une mesure correcte lorsque l'interrupteur est ouvert, une résistance de pull-up ou de pull-down doit être utilisée. L'objectif de cette résistance est d'assurer un état stable est prédictible lorsque l'interrupteur est ouvert. On utilise souvent une résistance de 10 K Ohm, suffisamment faible pour éviter l'état flottant du pin, mais suffisamment grande pour ne pas consommer trop de courant. Voir le tutoriel http://arduino.cc/en/Tutorial/DigitalReadSerial[Digital Read Serial^] pour plus d'informations.
[%hardbreaks]

Lorsqu'une résistance de pull-down est utilisée, alors le pin d'entrée sera à `LOW` quand l'interrupteur est ouvert, et à `HIGH` quand l'interrupteur est fermé.
[%hardbreaks]

Lorsqu'une résistance de pull-up est utilisée, alors le pin d'entrée sera à `HIGH` quand l'interrupteur est ouvert, et à `LOW` quand l'interrupteur est fermé.
[%hardbreaks]

[float]
=== Pins configuré comme INPUT_PULLUP
Le micro-contrôleur ATMega de l'Arduino a des résistances internes de pull-up (c'est-à-dire, connectées de manière interne au 5V ou 3.3V). Si vous préférez utiliser ces dernières, plutôt que des résistances externes de pull-up, alors vous pouvez passer l'argument `INPUT_PULLUP` avec la fonction `pinMode()`.
[%hardbreaks]

Voir le tutoriel the http://arduino.cc/en/Tutorial/InputPullupSerial[Input Pullup Serial^] pour étudier un exemple d'utilisation.
[%hardbreaks]

Les pins configurés comme entrées (`INPUT` ou `INPUT_PULLUP`) peuvent être endommagés s'ils sont connectés à des tensions inférieures à la masse (tensions négatives) ou supérieures à la tension d'alimentation (5V ou 3.3V).
[%hardbreaks]

[float]
=== Pins configurés comme OUTPUT
On dit que les pins configurés comme `OUTPUT` avec `pinMode()` sont dans un état de _basse impédance_. Cela veut dire qu'ils peuvent fournir une certaine quantité de courant à d'autres circuits. Les pins des ATMega peuvent fournir ou recevoir jusqu'à 40 mA (milli-ampère). Pour des charges supérieures à 40 mA (comme des moteurs), un transistor ou une autre interface de puissance sera nécessaire.
[%hardbreaks]

Les pins configurés comme sorties peuvent être endommagés s'ils sont connectée à la masse ou une tension forcée positive.
[%hardbreaks]

[float]
== Définition : LED_BUILTIN
La plupart des cartes Arduino ont un pin connecté à une LED intégrée, avec une résistance en série. La constante `LED_BUILTIN` est le numéro du pin auquel la LED est connectée. Pour la majorité des cartes, cette LED est branchée sur le pin 13.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

--
// HOW TO USE SECTION ENDS

// SEE ALSO  SECTION BEGINS
[#see_also]
--

[float]
=== Voir aussi

[role="language"]

--
// SEE ALSO SECTION ENDS
